title: Andrew Son
description: Personal Website
author: Andrew 
email: 
baseurl: ""
url: "https://andrew20241.github.io"

# Jekyll settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Author configuration
author:
  name: Andrew Son
  url: https://github.com/Andrew20241
  image: /assets/images/user.jpg

# Social links
social:
  github: Andrew20241

# Sass/SCSS settings
sass:
  load_paths:
    - /home/andrew/Documents/Andrew/assets/css
  style: compressed

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _sass
