title: Andrew
description: Portfolio & Projects
author: Andrew
email: your-email@example.com
baseurl: ""
url: "https://andrew20241.github.io"

# Jekyll settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Author configuration
author:
  name: Andrew
  url: https://github.com/Andrew20241
  image: /assets/images/user.jpg

# Social links
social:
  github: Andrew20241

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
